/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	activationv1alpha1 "k8s.io/api/activation/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ActivationPoolLister helps list ActivationPools.
// All objects returned here must be treated as read-only.
type ActivationPoolLister interface {
	// List lists all ActivationPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*activationv1alpha1.ActivationPool, err error)
	// ActivationPools returns an object that can list and get ActivationPools.
	ActivationPools(namespace string) ActivationPoolNamespaceLister
	ActivationPoolListerExpansion
}

// activationPoolLister implements the ActivationPoolLister interface.
type activationPoolLister struct {
	listers.ResourceIndexer[*activationv1alpha1.ActivationPool]
}

// NewActivationPoolLister returns a new ActivationPoolLister.
func NewActivationPoolLister(indexer cache.Indexer) ActivationPoolLister {
	return &activationPoolLister{listers.New[*activationv1alpha1.ActivationPool](indexer, activationv1alpha1.Resource("activationpool"))}
}

// ActivationPools returns an object that can list and get ActivationPools.
func (s *activationPoolLister) ActivationPools(namespace string) ActivationPoolNamespaceLister {
	return activationPoolNamespaceLister{listers.NewNamespaced[*activationv1alpha1.ActivationPool](s.ResourceIndexer, namespace)}
}

// ActivationPoolNamespaceLister helps list and get ActivationPools.
// All objects returned here must be treated as read-only.
type ActivationPoolNamespaceLister interface {
	// List lists all ActivationPools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*activationv1alpha1.ActivationPool, err error)
	// Get retrieves the ActivationPool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*activationv1alpha1.ActivationPool, error)
	ActivationPoolNamespaceListerExpansion
}

// activationPoolNamespaceLister implements the ActivationPoolNamespaceLister
// interface.
type activationPoolNamespaceLister struct {
	listers.ResourceIndexer[*activationv1alpha1.ActivationPool]
}
