/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ActivationSpecApplyConfiguration represents a declarative configuration of the ActivationSpec type for use
// with apply.
//
// ActivationSpec configures request-scoped bind behavior for the pool.
type ActivationSpecApplyConfiguration struct {
	// Deadline is the bind budget before the caller must fall back.
	// Defaults to 800ms when unset.
	Deadline *v1.Duration `json:"deadline,omitempty"`
	// Coalescing is the window in which concurrent demand is batched into one
	// refill operation. Defaults to 50ms when unset.
	Coalescing *v1.Duration `json:"coalescing,omitempty"`
}

// ActivationSpecApplyConfiguration constructs a declarative configuration of the ActivationSpec type for use with
// apply.
func ActivationSpec() *ActivationSpecApplyConfiguration {
	return &ActivationSpecApplyConfiguration{}
}

// WithDeadline sets the Deadline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deadline field is set to the value of the last call.
func (b *ActivationSpecApplyConfiguration) WithDeadline(value v1.Duration) *ActivationSpecApplyConfiguration {
	b.Deadline = &value
	return b
}

// WithCoalescing sets the Coalescing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Coalescing field is set to the value of the last call.
func (b *ActivationSpecApplyConfiguration) WithCoalescing(value v1.Duration) *ActivationSpecApplyConfiguration {
	b.Coalescing = &value
	return b
}
