/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// ActivationPoolSpecApplyConfiguration represents a declarative configuration of the ActivationPoolSpec type for use
// with apply.
//
// ActivationPoolSpec is the specification of an ActivationPool.
type ActivationPoolSpecApplyConfiguration struct {
	// TemplateRef references the PodTemplate used for capacity pods in this
	// pool. The referenced object must be in the same namespace as the pool.
	TemplateRef *v1.TypedLocalObjectReferenceApplyConfiguration `json:"templateRef,omitempty"`
	// Warm configures how many restore-ready / idle sandboxes to hold.
	Warm *WarmSpecApplyConfiguration `json:"warm,omitempty"`
	// Source optionally identifies a checkpoint used to top up the pool
	// (KEP-5823). Ignored for Phase 0 degraded-mode (idle pod) pools.
	Source *PoolSourceApplyConfiguration `json:"source,omitempty"`
	// Activation configures bind deadlines and demand coalescing.
	Activation *ActivationSpecApplyConfiguration `json:"activation,omitempty"`
	// Durability declares which durability tiers this pool can satisfy.
	// Activate binds only when the request's required tier is offered here.
	Durability *DurabilitySpecApplyConfiguration `json:"durability,omitempty"`
	// Supply configures how the pool asks for replenishment capacity.
	Supply *SupplySpecApplyConfiguration `json:"supply,omitempty"`
	// EndpointPort is the port published in Bound.endpoints for capacity pods
	// of this pool. PoC field until endpoints carry richer addressing.
	EndpointPort *int32 `json:"endpointPort,omitempty"`
	// PriorityClassName is applied to capacity pods created for this pool so
	// idle warm capacity remains reclaimable. PoC field.
	PriorityClassName *string `json:"priorityClassName,omitempty"`
}

// ActivationPoolSpecApplyConfiguration constructs a declarative configuration of the ActivationPoolSpec type for use with
// apply.
func ActivationPoolSpec() *ActivationPoolSpecApplyConfiguration {
	return &ActivationPoolSpecApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithTemplateRef(value *v1.TypedLocalObjectReferenceApplyConfiguration) *ActivationPoolSpecApplyConfiguration {
	b.TemplateRef = value
	return b
}

// WithWarm sets the Warm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Warm field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithWarm(value *WarmSpecApplyConfiguration) *ActivationPoolSpecApplyConfiguration {
	b.Warm = value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithSource(value *PoolSourceApplyConfiguration) *ActivationPoolSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithActivation sets the Activation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Activation field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithActivation(value *ActivationSpecApplyConfiguration) *ActivationPoolSpecApplyConfiguration {
	b.Activation = value
	return b
}

// WithDurability sets the Durability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Durability field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithDurability(value *DurabilitySpecApplyConfiguration) *ActivationPoolSpecApplyConfiguration {
	b.Durability = value
	return b
}

// WithSupply sets the Supply field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Supply field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithSupply(value *SupplySpecApplyConfiguration) *ActivationPoolSpecApplyConfiguration {
	b.Supply = value
	return b
}

// WithEndpointPort sets the EndpointPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndpointPort field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithEndpointPort(value int32) *ActivationPoolSpecApplyConfiguration {
	b.EndpointPort = &value
	return b
}

// WithPriorityClassName sets the PriorityClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityClassName field is set to the value of the last call.
func (b *ActivationPoolSpecApplyConfiguration) WithPriorityClassName(value string) *ActivationPoolSpecApplyConfiguration {
	b.PriorityClassName = &value
	return b
}
