/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	activationv1alpha1 "k8s.io/api/activation/v1alpha1"
)

// DurabilitySpecApplyConfiguration represents a declarative configuration of the DurabilitySpec type for use
// with apply.
//
// DurabilitySpec lists durability tiers the pool's runtime offers.
type DurabilitySpecApplyConfiguration struct {
	// Offered is the set of durability tiers this pool can satisfy.
	Offered []activationv1alpha1.DurabilityTier `json:"offered,omitempty"`
}

// DurabilitySpecApplyConfiguration constructs a declarative configuration of the DurabilitySpec type for use with
// apply.
func DurabilitySpec() *DurabilitySpecApplyConfiguration {
	return &DurabilitySpecApplyConfiguration{}
}

// WithOffered adds the given value to the Offered field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Offered field.
func (b *DurabilitySpecApplyConfiguration) WithOffered(values ...activationv1alpha1.DurabilityTier) *DurabilitySpecApplyConfiguration {
	for i := range values {
		b.Offered = append(b.Offered, values[i])
	}
	return b
}
