/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	activationv1alpha1 "k8s.io/api/activation/v1alpha1"
)

// SupplySpecApplyConfiguration represents a declarative configuration of the SupplySpec type for use
// with apply.
//
// SupplySpec configures how the pool signals demand for replenishment.
type SupplySpecApplyConfiguration struct {
	// CapacityRequestClass is a WAS provisioning class hook. Ignored until
	// CapacityRequest exists in-tree; Phase 0 demand is pending capacity pods.
	CapacityRequestClass *string `json:"capacityRequestClass,omitempty"`
	// DeviceClaimScope controls whether a ResourceClaim is held for the pool
	// lifetime or reallocated per activation.
	DeviceClaimScope *activationv1alpha1.DeviceClaimScope `json:"deviceClaimScope,omitempty"`
}

// SupplySpecApplyConfiguration constructs a declarative configuration of the SupplySpec type for use with
// apply.
func SupplySpec() *SupplySpecApplyConfiguration {
	return &SupplySpecApplyConfiguration{}
}

// WithCapacityRequestClass sets the CapacityRequestClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CapacityRequestClass field is set to the value of the last call.
func (b *SupplySpecApplyConfiguration) WithCapacityRequestClass(value string) *SupplySpecApplyConfiguration {
	b.CapacityRequestClass = &value
	return b
}

// WithDeviceClaimScope sets the DeviceClaimScope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceClaimScope field is set to the value of the last call.
func (b *SupplySpecApplyConfiguration) WithDeviceClaimScope(value activationv1alpha1.DeviceClaimScope) *SupplySpecApplyConfiguration {
	b.DeviceClaimScope = &value
	return b
}
