/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-codegen.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_ActivationPool = map[string]string{
	"":         "ActivationPool declares warm capacity for a workload template and how that pool replenishes. Routers bind ready capacity from a pool via the Activation gRPC contract (k8s.io/activation); this object is the control-plane declaration of the pool, not the bind path itself.",
	"metadata": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
	"spec":     "Spec defines the desired warm pool.",
	"status":   "Status is the most recently observed status of the pool.",
}

func (ActivationPool) SwaggerDoc() map[string]string {
	return map_ActivationPool
}

var map_ActivationPoolList = map[string]string{
	"":         "ActivationPoolList is a collection of ActivationPool objects.",
	"metadata": "Standard list metadata.",
	"items":    "Items is the list of ActivationPool objects.",
}

func (ActivationPoolList) SwaggerDoc() map[string]string {
	return map_ActivationPoolList
}

var map_ActivationPoolSpec = map[string]string{
	"":                  "ActivationPoolSpec is the specification of an ActivationPool.",
	"templateRef":       "TemplateRef references the PodTemplate used for capacity pods in this pool. The referenced object must be in the same namespace as the pool.",
	"warm":              "Warm configures how many restore-ready / idle sandboxes to hold.",
	"source":            "Source optionally identifies a checkpoint used to top up the pool (KEP-5823). Ignored for Phase 0 degraded-mode (idle pod) pools.",
	"activation":        "Activation configures bind deadlines and demand coalescing.",
	"durability":        "Durability declares which durability tiers this pool can satisfy. Activate binds only when the request's required tier is offered here.",
	"supply":            "Supply configures how the pool asks for replenishment capacity.",
	"endpointPort":      "EndpointPort is the port published in Bound.endpoints for capacity pods of this pool. PoC field until endpoints carry richer addressing.",
	"priorityClassName": "PriorityClassName is applied to capacity pods created for this pool so idle warm capacity remains reclaimable. PoC field.",
}

func (ActivationPoolSpec) SwaggerDoc() map[string]string {
	return map_ActivationPoolSpec
}

var map_ActivationPoolStatus = map[string]string{
	"":           "ActivationPoolStatus is the status of an ActivationPool.",
	"conditions": "Conditions represent the latest available observations of the pool.",
}

func (ActivationPoolStatus) SwaggerDoc() map[string]string {
	return map_ActivationPoolStatus
}

var map_ActivationSpec = map[string]string{
	"":           "ActivationSpec configures request-scoped bind behavior for the pool.",
	"deadline":   "Deadline is the bind budget before the caller must fall back. Defaults to 800ms when unset.",
	"coalescing": "Coalescing is the window in which concurrent demand is batched into one refill operation. Defaults to 50ms when unset.",
}

func (ActivationSpec) SwaggerDoc() map[string]string {
	return map_ActivationSpec
}

var map_DurabilitySpec = map[string]string{
	"":        "DurabilitySpec lists durability tiers the pool's runtime offers.",
	"offered": "Offered is the set of durability tiers this pool can satisfy.",
}

func (DurabilitySpec) SwaggerDoc() map[string]string {
	return map_DurabilitySpec
}

var map_PoolSource = map[string]string{
	"":              "PoolSource identifies optional warm-state provenance for the pool.",
	"checkpointRef": "CheckpointRef names a checkpoint artifact (KEP-5823) used for restore hits. Opaque string for Phase 0; restore path is Phase 2.",
}

func (PoolSource) SwaggerDoc() map[string]string {
	return map_PoolSource
}

var map_SupplySpec = map[string]string{
	"":                     "SupplySpec configures how the pool signals demand for replenishment.",
	"capacityRequestClass": "CapacityRequestClass is a WAS provisioning class hook. Ignored until CapacityRequest exists in-tree; Phase 0 demand is pending capacity pods.",
	"deviceClaimScope":     "DeviceClaimScope controls whether a ResourceClaim is held for the pool lifetime or reallocated per activation.",
}

func (SupplySpec) SwaggerDoc() map[string]string {
	return map_SupplySpec
}

var map_WarmSpec = map[string]string{
	"":    "WarmSpec configures the warm floor and ceiling for a pool.",
	"min": "Min is the number of warm sandboxes the refill controller should try to maintain. Must be >= 0.",
	"max": "Max is the upper bound on warm sandboxes. Must be >= Min.",
}

func (WarmSpec) SwaggerDoc() map[string]string {
	return map_WarmSpec
}

// AUTO-GENERATED FUNCTIONS END HERE
