//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	activationv1alpha1 "k8s.io/api/activation/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	activation "k8s.io/kubernetes/pkg/apis/activation"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.ActivationPool)(nil), (*activation.ActivationPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ActivationPool_To_activation_ActivationPool(a.(*activationv1alpha1.ActivationPool), b.(*activation.ActivationPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.ActivationPool)(nil), (*activationv1alpha1.ActivationPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_ActivationPool_To_v1alpha1_ActivationPool(a.(*activation.ActivationPool), b.(*activationv1alpha1.ActivationPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.ActivationPoolList)(nil), (*activation.ActivationPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ActivationPoolList_To_activation_ActivationPoolList(a.(*activationv1alpha1.ActivationPoolList), b.(*activation.ActivationPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.ActivationPoolList)(nil), (*activationv1alpha1.ActivationPoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_ActivationPoolList_To_v1alpha1_ActivationPoolList(a.(*activation.ActivationPoolList), b.(*activationv1alpha1.ActivationPoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.ActivationPoolSpec)(nil), (*activation.ActivationPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ActivationPoolSpec_To_activation_ActivationPoolSpec(a.(*activationv1alpha1.ActivationPoolSpec), b.(*activation.ActivationPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.ActivationPoolSpec)(nil), (*activationv1alpha1.ActivationPoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_ActivationPoolSpec_To_v1alpha1_ActivationPoolSpec(a.(*activation.ActivationPoolSpec), b.(*activationv1alpha1.ActivationPoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.ActivationPoolStatus)(nil), (*activation.ActivationPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ActivationPoolStatus_To_activation_ActivationPoolStatus(a.(*activationv1alpha1.ActivationPoolStatus), b.(*activation.ActivationPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.ActivationPoolStatus)(nil), (*activationv1alpha1.ActivationPoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_ActivationPoolStatus_To_v1alpha1_ActivationPoolStatus(a.(*activation.ActivationPoolStatus), b.(*activationv1alpha1.ActivationPoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.ActivationSpec)(nil), (*activation.ActivationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ActivationSpec_To_activation_ActivationSpec(a.(*activationv1alpha1.ActivationSpec), b.(*activation.ActivationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.ActivationSpec)(nil), (*activationv1alpha1.ActivationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_ActivationSpec_To_v1alpha1_ActivationSpec(a.(*activation.ActivationSpec), b.(*activationv1alpha1.ActivationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.DurabilitySpec)(nil), (*activation.DurabilitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DurabilitySpec_To_activation_DurabilitySpec(a.(*activationv1alpha1.DurabilitySpec), b.(*activation.DurabilitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.DurabilitySpec)(nil), (*activationv1alpha1.DurabilitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_DurabilitySpec_To_v1alpha1_DurabilitySpec(a.(*activation.DurabilitySpec), b.(*activationv1alpha1.DurabilitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.PoolSource)(nil), (*activation.PoolSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PoolSource_To_activation_PoolSource(a.(*activationv1alpha1.PoolSource), b.(*activation.PoolSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.PoolSource)(nil), (*activationv1alpha1.PoolSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_PoolSource_To_v1alpha1_PoolSource(a.(*activation.PoolSource), b.(*activationv1alpha1.PoolSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.SupplySpec)(nil), (*activation.SupplySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SupplySpec_To_activation_SupplySpec(a.(*activationv1alpha1.SupplySpec), b.(*activation.SupplySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.SupplySpec)(nil), (*activationv1alpha1.SupplySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_SupplySpec_To_v1alpha1_SupplySpec(a.(*activation.SupplySpec), b.(*activationv1alpha1.SupplySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activationv1alpha1.WarmSpec)(nil), (*activation.WarmSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WarmSpec_To_activation_WarmSpec(a.(*activationv1alpha1.WarmSpec), b.(*activation.WarmSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*activation.WarmSpec)(nil), (*activationv1alpha1.WarmSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_activation_WarmSpec_To_v1alpha1_WarmSpec(a.(*activation.WarmSpec), b.(*activationv1alpha1.WarmSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ActivationPool_To_activation_ActivationPool(in *activationv1alpha1.ActivationPool, out *activation.ActivationPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ActivationPoolSpec_To_activation_ActivationPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ActivationPoolStatus_To_activation_ActivationPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ActivationPool_To_activation_ActivationPool is an autogenerated conversion function.
func Convert_v1alpha1_ActivationPool_To_activation_ActivationPool(in *activationv1alpha1.ActivationPool, out *activation.ActivationPool, s conversion.Scope) error {
	return autoConvert_v1alpha1_ActivationPool_To_activation_ActivationPool(in, out, s)
}

func autoConvert_activation_ActivationPool_To_v1alpha1_ActivationPool(in *activation.ActivationPool, out *activationv1alpha1.ActivationPool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_activation_ActivationPoolSpec_To_v1alpha1_ActivationPoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_activation_ActivationPoolStatus_To_v1alpha1_ActivationPoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_activation_ActivationPool_To_v1alpha1_ActivationPool is an autogenerated conversion function.
func Convert_activation_ActivationPool_To_v1alpha1_ActivationPool(in *activation.ActivationPool, out *activationv1alpha1.ActivationPool, s conversion.Scope) error {
	return autoConvert_activation_ActivationPool_To_v1alpha1_ActivationPool(in, out, s)
}

func autoConvert_v1alpha1_ActivationPoolList_To_activation_ActivationPoolList(in *activationv1alpha1.ActivationPoolList, out *activation.ActivationPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]activation.ActivationPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ActivationPoolList_To_activation_ActivationPoolList is an autogenerated conversion function.
func Convert_v1alpha1_ActivationPoolList_To_activation_ActivationPoolList(in *activationv1alpha1.ActivationPoolList, out *activation.ActivationPoolList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ActivationPoolList_To_activation_ActivationPoolList(in, out, s)
}

func autoConvert_activation_ActivationPoolList_To_v1alpha1_ActivationPoolList(in *activation.ActivationPoolList, out *activationv1alpha1.ActivationPoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]activationv1alpha1.ActivationPool)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_activation_ActivationPoolList_To_v1alpha1_ActivationPoolList is an autogenerated conversion function.
func Convert_activation_ActivationPoolList_To_v1alpha1_ActivationPoolList(in *activation.ActivationPoolList, out *activationv1alpha1.ActivationPoolList, s conversion.Scope) error {
	return autoConvert_activation_ActivationPoolList_To_v1alpha1_ActivationPoolList(in, out, s)
}

func autoConvert_v1alpha1_ActivationPoolSpec_To_activation_ActivationPoolSpec(in *activationv1alpha1.ActivationPoolSpec, out *activation.ActivationPoolSpec, s conversion.Scope) error {
	*out = *(*activation.ActivationPoolSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ActivationPoolSpec_To_activation_ActivationPoolSpec is an autogenerated conversion function.
func Convert_v1alpha1_ActivationPoolSpec_To_activation_ActivationPoolSpec(in *activationv1alpha1.ActivationPoolSpec, out *activation.ActivationPoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ActivationPoolSpec_To_activation_ActivationPoolSpec(in, out, s)
}

func autoConvert_activation_ActivationPoolSpec_To_v1alpha1_ActivationPoolSpec(in *activation.ActivationPoolSpec, out *activationv1alpha1.ActivationPoolSpec, s conversion.Scope) error {
	*out = *(*activationv1alpha1.ActivationPoolSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_activation_ActivationPoolSpec_To_v1alpha1_ActivationPoolSpec is an autogenerated conversion function.
func Convert_activation_ActivationPoolSpec_To_v1alpha1_ActivationPoolSpec(in *activation.ActivationPoolSpec, out *activationv1alpha1.ActivationPoolSpec, s conversion.Scope) error {
	return autoConvert_activation_ActivationPoolSpec_To_v1alpha1_ActivationPoolSpec(in, out, s)
}

func autoConvert_v1alpha1_ActivationPoolStatus_To_activation_ActivationPoolStatus(in *activationv1alpha1.ActivationPoolStatus, out *activation.ActivationPoolStatus, s conversion.Scope) error {
	*out = *(*activation.ActivationPoolStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ActivationPoolStatus_To_activation_ActivationPoolStatus is an autogenerated conversion function.
func Convert_v1alpha1_ActivationPoolStatus_To_activation_ActivationPoolStatus(in *activationv1alpha1.ActivationPoolStatus, out *activation.ActivationPoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ActivationPoolStatus_To_activation_ActivationPoolStatus(in, out, s)
}

func autoConvert_activation_ActivationPoolStatus_To_v1alpha1_ActivationPoolStatus(in *activation.ActivationPoolStatus, out *activationv1alpha1.ActivationPoolStatus, s conversion.Scope) error {
	*out = *(*activationv1alpha1.ActivationPoolStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_activation_ActivationPoolStatus_To_v1alpha1_ActivationPoolStatus is an autogenerated conversion function.
func Convert_activation_ActivationPoolStatus_To_v1alpha1_ActivationPoolStatus(in *activation.ActivationPoolStatus, out *activationv1alpha1.ActivationPoolStatus, s conversion.Scope) error {
	return autoConvert_activation_ActivationPoolStatus_To_v1alpha1_ActivationPoolStatus(in, out, s)
}

func autoConvert_v1alpha1_ActivationSpec_To_activation_ActivationSpec(in *activationv1alpha1.ActivationSpec, out *activation.ActivationSpec, s conversion.Scope) error {
	*out = *(*activation.ActivationSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ActivationSpec_To_activation_ActivationSpec is an autogenerated conversion function.
func Convert_v1alpha1_ActivationSpec_To_activation_ActivationSpec(in *activationv1alpha1.ActivationSpec, out *activation.ActivationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ActivationSpec_To_activation_ActivationSpec(in, out, s)
}

func autoConvert_activation_ActivationSpec_To_v1alpha1_ActivationSpec(in *activation.ActivationSpec, out *activationv1alpha1.ActivationSpec, s conversion.Scope) error {
	*out = *(*activationv1alpha1.ActivationSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_activation_ActivationSpec_To_v1alpha1_ActivationSpec is an autogenerated conversion function.
func Convert_activation_ActivationSpec_To_v1alpha1_ActivationSpec(in *activation.ActivationSpec, out *activationv1alpha1.ActivationSpec, s conversion.Scope) error {
	return autoConvert_activation_ActivationSpec_To_v1alpha1_ActivationSpec(in, out, s)
}

func autoConvert_v1alpha1_DurabilitySpec_To_activation_DurabilitySpec(in *activationv1alpha1.DurabilitySpec, out *activation.DurabilitySpec, s conversion.Scope) error {
	*out = *(*activation.DurabilitySpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DurabilitySpec_To_activation_DurabilitySpec is an autogenerated conversion function.
func Convert_v1alpha1_DurabilitySpec_To_activation_DurabilitySpec(in *activationv1alpha1.DurabilitySpec, out *activation.DurabilitySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DurabilitySpec_To_activation_DurabilitySpec(in, out, s)
}

func autoConvert_activation_DurabilitySpec_To_v1alpha1_DurabilitySpec(in *activation.DurabilitySpec, out *activationv1alpha1.DurabilitySpec, s conversion.Scope) error {
	*out = *(*activationv1alpha1.DurabilitySpec)(unsafe.Pointer(in))
	return nil
}

// Convert_activation_DurabilitySpec_To_v1alpha1_DurabilitySpec is an autogenerated conversion function.
func Convert_activation_DurabilitySpec_To_v1alpha1_DurabilitySpec(in *activation.DurabilitySpec, out *activationv1alpha1.DurabilitySpec, s conversion.Scope) error {
	return autoConvert_activation_DurabilitySpec_To_v1alpha1_DurabilitySpec(in, out, s)
}

func autoConvert_v1alpha1_PoolSource_To_activation_PoolSource(in *activationv1alpha1.PoolSource, out *activation.PoolSource, s conversion.Scope) error {
	*out = *(*activation.PoolSource)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_PoolSource_To_activation_PoolSource is an autogenerated conversion function.
func Convert_v1alpha1_PoolSource_To_activation_PoolSource(in *activationv1alpha1.PoolSource, out *activation.PoolSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_PoolSource_To_activation_PoolSource(in, out, s)
}

func autoConvert_activation_PoolSource_To_v1alpha1_PoolSource(in *activation.PoolSource, out *activationv1alpha1.PoolSource, s conversion.Scope) error {
	*out = *(*activationv1alpha1.PoolSource)(unsafe.Pointer(in))
	return nil
}

// Convert_activation_PoolSource_To_v1alpha1_PoolSource is an autogenerated conversion function.
func Convert_activation_PoolSource_To_v1alpha1_PoolSource(in *activation.PoolSource, out *activationv1alpha1.PoolSource, s conversion.Scope) error {
	return autoConvert_activation_PoolSource_To_v1alpha1_PoolSource(in, out, s)
}

func autoConvert_v1alpha1_SupplySpec_To_activation_SupplySpec(in *activationv1alpha1.SupplySpec, out *activation.SupplySpec, s conversion.Scope) error {
	*out = *(*activation.SupplySpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_SupplySpec_To_activation_SupplySpec is an autogenerated conversion function.
func Convert_v1alpha1_SupplySpec_To_activation_SupplySpec(in *activationv1alpha1.SupplySpec, out *activation.SupplySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SupplySpec_To_activation_SupplySpec(in, out, s)
}

func autoConvert_activation_SupplySpec_To_v1alpha1_SupplySpec(in *activation.SupplySpec, out *activationv1alpha1.SupplySpec, s conversion.Scope) error {
	*out = *(*activationv1alpha1.SupplySpec)(unsafe.Pointer(in))
	return nil
}

// Convert_activation_SupplySpec_To_v1alpha1_SupplySpec is an autogenerated conversion function.
func Convert_activation_SupplySpec_To_v1alpha1_SupplySpec(in *activation.SupplySpec, out *activationv1alpha1.SupplySpec, s conversion.Scope) error {
	return autoConvert_activation_SupplySpec_To_v1alpha1_SupplySpec(in, out, s)
}

func autoConvert_v1alpha1_WarmSpec_To_activation_WarmSpec(in *activationv1alpha1.WarmSpec, out *activation.WarmSpec, s conversion.Scope) error {
	*out = *(*activation.WarmSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_WarmSpec_To_activation_WarmSpec is an autogenerated conversion function.
func Convert_v1alpha1_WarmSpec_To_activation_WarmSpec(in *activationv1alpha1.WarmSpec, out *activation.WarmSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_WarmSpec_To_activation_WarmSpec(in, out, s)
}

func autoConvert_activation_WarmSpec_To_v1alpha1_WarmSpec(in *activation.WarmSpec, out *activationv1alpha1.WarmSpec, s conversion.Scope) error {
	*out = *(*activationv1alpha1.WarmSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_activation_WarmSpec_To_v1alpha1_WarmSpec is an autogenerated conversion function.
func Convert_activation_WarmSpec_To_v1alpha1_WarmSpec(in *activation.WarmSpec, out *activationv1alpha1.WarmSpec, s conversion.Scope) error {
	return autoConvert_activation_WarmSpec_To_v1alpha1_WarmSpec(in, out, s)
}
