/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
//Copyright 2026 The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// To regenerate api.pb.go run `hack/update-codegen.sh protobindings`

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: staging/src/k8s.io/activation/apis/v1alpha1/api.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DurabilityTier int32

const (
	// Journal write may lag the bind. Fenced and crash-safe (no corruption),
	// but the session can be lost on node death before the journal commits.
	DurabilityTier_BEST_EFFORT_DURABLE DurabilityTier = 0
	// Read-your-writes-durable before first response. Binds only on a
	// durability-capable runtime; pays an explicit commit-latency floor.
	DurabilityTier_SYNC_DURABLE_CREATE DurabilityTier = 1
)

// Enum value maps for DurabilityTier.
var (
	DurabilityTier_name = map[int32]string{
		0: "BEST_EFFORT_DURABLE",
		1: "SYNC_DURABLE_CREATE",
	}
	DurabilityTier_value = map[string]int32{
		"BEST_EFFORT_DURABLE": 0,
		"SYNC_DURABLE_CREATE": 1,
	}
)

func (x DurabilityTier) Enum() *DurabilityTier {
	p := new(DurabilityTier)
	*p = x
	return p
}

func (x DurabilityTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DurabilityTier) Descriptor() protoreflect.EnumDescriptor {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_enumTypes[0].Descriptor()
}

func (DurabilityTier) Type() protoreflect.EnumType {
	return &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_enumTypes[0]
}

func (x DurabilityTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DurabilityTier.Descriptor instead.
func (DurabilityTier) EnumDescriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

type ActivateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pool is the namespaced ActivationPool name to bind from.
	// Format: "<namespace>/<name>" or just "<name>" when namespace is implied by authz context.
	Pool string `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	// count is the number of sandboxes to bind in one call.
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// deadline_ms is the bind budget for this call in milliseconds.
	// If zero, the pool's spec.activation.deadline applies.
	// int64 ms (not google.protobuf.Duration): in-tree gRPC api.proto files do not
	// import well-known Duration, and third_party/protobuf lacks duration.proto.
	DeadlineMs int64 `protobuf:"varint,3,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	// durability is the required durability tier. Default BEST_EFFORT_DURABLE.
	Durability    DurabilityTier `protobuf:"varint,4,opt,name=durability,proto3,enum=k8s.io.activation.apis.v1alpha1.DurabilityTier" json:"durability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *ActivateRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ActivateRequest) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *ActivateRequest) GetDurability() DurabilityTier {
	if x != nil {
		return x.Durability
	}
	return DurabilityTier_BEST_EFFORT_DURABLE
}

type ActivateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ActivateResponse_Bound
	//	*ActivateResponse_Deferred
	Result        isActivateResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ActivateResponse) GetResult() isActivateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActivateResponse) GetBound() *Bound {
	if x != nil {
		if x, ok := x.Result.(*ActivateResponse_Bound); ok {
			return x.Bound
		}
	}
	return nil
}

func (x *ActivateResponse) GetDeferred() *Deferred {
	if x != nil {
		if x, ok := x.Result.(*ActivateResponse_Deferred); ok {
			return x.Deferred
		}
	}
	return nil
}

type isActivateResponse_Result interface {
	isActivateResponse_Result()
}

type ActivateResponse_Bound struct {
	Bound *Bound `protobuf:"bytes,1,opt,name=bound,proto3,oneof"`
}

type ActivateResponse_Deferred struct {
	// Deferred is returned on miss, deadline exceeded, or durability mismatch.
	// Renamed from Pending to avoid colliding with the Pending pod phase.
	Deferred *Deferred `protobuf:"bytes,2,opt,name=deferred,proto3,oneof"`
}

func (*ActivateResponse_Bound) isActivateResponse_Result() {}

func (*ActivateResponse_Deferred) isActivateResponse_Result() {}

type Bound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// endpoints are the ready addresses for the bound sandbox(es).
	Endpoints []*Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// bind_generation is monotonic per sandbox; the sandbox rejects any
	// request carrying a stale generation.
	BindGeneration uint64 `protobuf:"varint,2,opt,name=bind_generation,json=bindGeneration,proto3" json:"bind_generation,omitempty"`
	// sandbox_id identifies the bound capacity pod (typically the pod UID).
	SandboxId     string `protobuf:"bytes,3,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bound) Reset() {
	*x = Bound{}
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bound) ProtoMessage() {}

func (x *Bound) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bound.ProtoReflect.Descriptor instead.
func (*Bound) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{2}
}

func (x *Bound) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Bound) GetBindGeneration() uint64 {
	if x != nil {
		return x.BindGeneration
	}
	return 0
}

func (x *Bound) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Deferred struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reason explains why the bind did not complete within the deadline.
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// message is a human-readable detail.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deferred) Reset() {
	*x = Deferred{}
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deferred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deferred) ProtoMessage() {}

func (x *Deferred) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deferred.ProtoReflect.Descriptor instead.
func (*Deferred) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{4}
}

func (x *Deferred) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Deferred) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DemandReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pool is the ActivationPool the demand applies to.
	Pool string `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	// pending is the number of outstanding requests waiting on this pool.
	Pending       uint32 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandReport) Reset() {
	*x = DemandReport{}
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandReport) ProtoMessage() {}

func (x *DemandReport) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandReport.ProtoReflect.Descriptor instead.
func (*DemandReport) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{5}
}

func (x *DemandReport) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *DemandReport) GetPending() uint32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type DemandAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// backpressure advises routers to shift traffic before the pool is empty.
	// Higher values mean stronger pressure; 0 means none.
	Backpressure  uint32 `protobuf:"varint,1,opt,name=backpressure,proto3" json:"backpressure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandAck) Reset() {
	*x = DemandAck{}
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandAck) ProtoMessage() {}

func (x *DemandAck) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandAck.ProtoReflect.Descriptor instead.
func (*DemandAck) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP(), []int{6}
}

func (x *DemandAck) GetBackpressure() uint32 {
	if x != nil {
		return x.Backpressure
	}
	return 0
}

var File_staging_src_k8s_io_activation_apis_v1alpha1_api_proto protoreflect.FileDescriptor

const file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"5staging/src/k8s.io/activation/apis/v1alpha1/api.proto\x12\x1fk8s.io.activation.apis.v1alpha1\"\xad\x01\n" +
	"\x0fActivateRequest\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1f\n" +
	"\vdeadline_ms\x18\x03 \x01(\x03R\n" +
	"deadlineMs\x12O\n" +
	"\n" +
	"durability\x18\x04 \x01(\x0e2/.k8s.io.activation.apis.v1alpha1.DurabilityTierR\n" +
	"durability\"\xa5\x01\n" +
	"\x10ActivateResponse\x12>\n" +
	"\x05bound\x18\x01 \x01(\v2&.k8s.io.activation.apis.v1alpha1.BoundH\x00R\x05bound\x12G\n" +
	"\bdeferred\x18\x02 \x01(\v2).k8s.io.activation.apis.v1alpha1.DeferredH\x00R\bdeferredB\b\n" +
	"\x06result\"\x98\x01\n" +
	"\x05Bound\x12G\n" +
	"\tendpoints\x18\x01 \x03(\v2).k8s.io.activation.apis.v1alpha1.EndpointR\tendpoints\x12'\n" +
	"\x0fbind_generation\x18\x02 \x01(\x04R\x0ebindGeneration\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x03 \x01(\tR\tsandboxId\"8\n" +
	"\bEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"<\n" +
	"\bDeferred\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\fDemandReport\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x18\n" +
	"\apending\x18\x02 \x01(\rR\apending\"/\n" +
	"\tDemandAck\x12\"\n" +
	"\fbackpressure\x18\x01 \x01(\rR\fbackpressure*B\n" +
	"\x0eDurabilityTier\x12\x17\n" +
	"\x13BEST_EFFORT_DURABLE\x10\x00\x12\x17\n" +
	"\x13SYNC_DURABLE_CREATE\x10\x012\xe8\x01\n" +
	"\n" +
	"Activation\x12o\n" +
	"\bActivate\x120.k8s.io.activation.apis.v1alpha1.ActivateRequest\x1a1.k8s.io.activation.apis.v1alpha1.ActivateResponse\x12i\n" +
	"\fReportDemand\x12-.k8s.io.activation.apis.v1alpha1.DemandReport\x1a*.k8s.io.activation.apis.v1alpha1.DemandAckB!Z\x1fk8s.io/activation/apis/v1alpha1b\x06proto3"

var (
	file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescOnce sync.Once
	file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescData []byte
)

func file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDesc), len(file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDesc)))
	})
	return file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDescData
}

var file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_goTypes = []any{
	(DurabilityTier)(0),      // 0: k8s.io.activation.apis.v1alpha1.DurabilityTier
	(*ActivateRequest)(nil),  // 1: k8s.io.activation.apis.v1alpha1.ActivateRequest
	(*ActivateResponse)(nil), // 2: k8s.io.activation.apis.v1alpha1.ActivateResponse
	(*Bound)(nil),            // 3: k8s.io.activation.apis.v1alpha1.Bound
	(*Endpoint)(nil),         // 4: k8s.io.activation.apis.v1alpha1.Endpoint
	(*Deferred)(nil),         // 5: k8s.io.activation.apis.v1alpha1.Deferred
	(*DemandReport)(nil),     // 6: k8s.io.activation.apis.v1alpha1.DemandReport
	(*DemandAck)(nil),        // 7: k8s.io.activation.apis.v1alpha1.DemandAck
}
var file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_depIdxs = []int32{
	0, // 0: k8s.io.activation.apis.v1alpha1.ActivateRequest.durability:type_name -> k8s.io.activation.apis.v1alpha1.DurabilityTier
	3, // 1: k8s.io.activation.apis.v1alpha1.ActivateResponse.bound:type_name -> k8s.io.activation.apis.v1alpha1.Bound
	5, // 2: k8s.io.activation.apis.v1alpha1.ActivateResponse.deferred:type_name -> k8s.io.activation.apis.v1alpha1.Deferred
	4, // 3: k8s.io.activation.apis.v1alpha1.Bound.endpoints:type_name -> k8s.io.activation.apis.v1alpha1.Endpoint
	1, // 4: k8s.io.activation.apis.v1alpha1.Activation.Activate:input_type -> k8s.io.activation.apis.v1alpha1.ActivateRequest
	6, // 5: k8s.io.activation.apis.v1alpha1.Activation.ReportDemand:input_type -> k8s.io.activation.apis.v1alpha1.DemandReport
	2, // 6: k8s.io.activation.apis.v1alpha1.Activation.Activate:output_type -> k8s.io.activation.apis.v1alpha1.ActivateResponse
	7, // 7: k8s.io.activation.apis.v1alpha1.Activation.ReportDemand:output_type -> k8s.io.activation.apis.v1alpha1.DemandAck
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_init() }
func file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_init() {
	if File_staging_src_k8s_io_activation_apis_v1alpha1_api_proto != nil {
		return
	}
	file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes[1].OneofWrappers = []any{
		(*ActivateResponse_Bound)(nil),
		(*ActivateResponse_Deferred)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDesc), len(file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_depIdxs,
		EnumInfos:         file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_enumTypes,
		MessageInfos:      file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_staging_src_k8s_io_activation_apis_v1alpha1_api_proto = out.File
	file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_goTypes = nil
	file_staging_src_k8s_io_activation_apis_v1alpha1_api_proto_depIdxs = nil
}
