/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
//Copyright 2026 The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// To regenerate api.pb.go run `hack/update-codegen.sh protobindings`

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.23.4
// source: staging/src/k8s.io/activation/apis/v1alpha1/api.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Activation_Activate_FullMethodName     = "/k8s.io.activation.apis.v1alpha1.Activation/Activate"
	Activation_ReportDemand_FullMethodName = "/k8s.io.activation.apis.v1alpha1.Activation/ReportDemand"
)

// ActivationClient is the client API for Activation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Activation is the synchronous activation contract: report demand for a pool
// and receive bound, ready capacity within a request-scoped deadline.
type ActivationClient interface {
	// Activate blocks up to deadline for bound, ready capacity.
	// It does NOT execute a turn — execution is a separate exchange against
	// the returned endpoint.
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	// ReportDemand is an aggregate demand hint used to refill pools ahead of need.
	ReportDemand(ctx context.Context, in *DemandReport, opts ...grpc.CallOption) (*DemandAck, error)
}

type activationClient struct {
	cc grpc.ClientConnInterface
}

func NewActivationClient(cc grpc.ClientConnInterface) ActivationClient {
	return &activationClient{cc}
}

func (c *activationClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, Activation_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activationClient) ReportDemand(ctx context.Context, in *DemandReport, opts ...grpc.CallOption) (*DemandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemandAck)
	err := c.cc.Invoke(ctx, Activation_ReportDemand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivationServer is the server API for Activation service.
// All implementations must embed UnimplementedActivationServer
// for forward compatibility.
//
// Activation is the synchronous activation contract: report demand for a pool
// and receive bound, ready capacity within a request-scoped deadline.
type ActivationServer interface {
	// Activate blocks up to deadline for bound, ready capacity.
	// It does NOT execute a turn — execution is a separate exchange against
	// the returned endpoint.
	Activate(context.Context, *ActivateRequest) (*ActivateResponse, error)
	// ReportDemand is an aggregate demand hint used to refill pools ahead of need.
	ReportDemand(context.Context, *DemandReport) (*DemandAck, error)
	mustEmbedUnimplementedActivationServer()
}

// UnimplementedActivationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivationServer struct{}

func (UnimplementedActivationServer) Activate(context.Context, *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedActivationServer) ReportDemand(context.Context, *DemandReport) (*DemandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDemand not implemented")
}
func (UnimplementedActivationServer) mustEmbedUnimplementedActivationServer() {}
func (UnimplementedActivationServer) testEmbeddedByValue()                    {}

// UnsafeActivationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivationServer will
// result in compilation errors.
type UnsafeActivationServer interface {
	mustEmbedUnimplementedActivationServer()
}

func RegisterActivationServer(s grpc.ServiceRegistrar, srv ActivationServer) {
	// If the following call panics, it indicates UnimplementedActivationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Activation_ServiceDesc, srv)
}

func _Activation_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivationServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activation_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivationServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activation_ReportDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemandReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivationServer).ReportDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activation_ReportDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivationServer).ReportDemand(ctx, req.(*DemandReport))
	}
	return interceptor(ctx, in, info, handler)
}

// Activation_ServiceDesc is the grpc.ServiceDesc for Activation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Activation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8s.io.activation.apis.v1alpha1.Activation",
	HandlerType: (*ActivationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Activate",
			Handler:    _Activation_Activate_Handler,
		},
		{
			MethodName: "ReportDemand",
			Handler:    _Activation_ReportDemand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staging/src/k8s.io/activation/apis/v1alpha1/api.proto",
}
