/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	activationv1alpha1 "k8s.io/api/activation/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsactivationv1alpha1 "k8s.io/client-go/applyconfigurations/activation/v1alpha1"
	gentype "k8s.io/client-go/gentype"
	scheme "k8s.io/client-go/kubernetes/scheme"
)

// ActivationPoolsGetter has a method to return a ActivationPoolInterface.
// A group's client should implement this interface.
type ActivationPoolsGetter interface {
	ActivationPools(namespace string) ActivationPoolInterface
}

// ActivationPoolInterface has methods to work with ActivationPool resources.
type ActivationPoolInterface interface {
	Create(ctx context.Context, activationPool *activationv1alpha1.ActivationPool, opts v1.CreateOptions) (*activationv1alpha1.ActivationPool, error)
	Update(ctx context.Context, activationPool *activationv1alpha1.ActivationPool, opts v1.UpdateOptions) (*activationv1alpha1.ActivationPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, activationPool *activationv1alpha1.ActivationPool, opts v1.UpdateOptions) (*activationv1alpha1.ActivationPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*activationv1alpha1.ActivationPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*activationv1alpha1.ActivationPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *activationv1alpha1.ActivationPool, err error)
	Apply(ctx context.Context, activationPool *applyconfigurationsactivationv1alpha1.ActivationPoolApplyConfiguration, opts v1.ApplyOptions) (result *activationv1alpha1.ActivationPool, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, activationPool *applyconfigurationsactivationv1alpha1.ActivationPoolApplyConfiguration, opts v1.ApplyOptions) (result *activationv1alpha1.ActivationPool, err error)
	ActivationPoolExpansion
}

// activationPools implements ActivationPoolInterface
type activationPools struct {
	*gentype.ClientWithListAndApply[*activationv1alpha1.ActivationPool, *activationv1alpha1.ActivationPoolList, *applyconfigurationsactivationv1alpha1.ActivationPoolApplyConfiguration]
}

// newActivationPools returns a ActivationPools
func newActivationPools(c *ActivationV1alpha1Client, namespace string) *activationPools {
	return &activationPools{
		gentype.NewClientWithListAndApply[*activationv1alpha1.ActivationPool, *activationv1alpha1.ActivationPoolList, *applyconfigurationsactivationv1alpha1.ActivationPoolApplyConfiguration](
			"activationpools",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *activationv1alpha1.ActivationPool { return &activationv1alpha1.ActivationPool{} },
			func() *activationv1alpha1.ActivationPoolList { return &activationv1alpha1.ActivationPoolList{} },
			gentype.PrefersProtobuf[*activationv1alpha1.ActivationPool](),
		),
	}
}
