/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiactivationv1alpha1 "k8s.io/api/activation/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	internalinterfaces "k8s.io/client-go/informers/internalinterfaces"
	kubernetes "k8s.io/client-go/kubernetes"
	activationv1alpha1 "k8s.io/client-go/listers/activation/v1alpha1"
	cache "k8s.io/client-go/tools/cache"
)

// ActivationPoolInformer provides access to a shared informer and lister for
// ActivationPools. Prefer using the type-safe variant (see [TypedActivationPoolInformer]).
type ActivationPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() activationv1alpha1.ActivationPoolLister
}

// TypedActivationPoolInformer provides access to a shared informer and lister for
// ActivationPools, including the type-safe TypedInformer variant.
// It is a superset of ActivationPoolInformer.
type TypedActivationPoolInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ActivationPoolIndexInformer
	Lister() activationv1alpha1.ActivationPoolLister
}

// ActivationPoolIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ActivationPoolIndexInformer cache.TypedSharedIndexInformer[*apiactivationv1alpha1.ActivationPool]

// ActivationPoolHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for ActivationPool.
type ActivationPoolHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiactivationv1alpha1.ActivationPool]

// ActivationPoolDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for ActivationPool.
type ActivationPoolDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiactivationv1alpha1.ActivationPool]

// ActivationPoolFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for ActivationPool.
type ActivationPoolFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiactivationv1alpha1.ActivationPool]

// ActivationPoolIndexers is a specialization of [cache.TypedIndexers] for ActivationPool.
type ActivationPoolIndexers = cache.TypedIndexers[*apiactivationv1alpha1.ActivationPool]

// DeletedActivationPool is a specialization of [cache.DeletedObject] for ActivationPool.
type DeletedActivationPool = cache.DeletedObject[*apiactivationv1alpha1.ActivationPool]

type activationPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewActivationPoolInformer constructs a new informer for ActivationPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedActivationPoolInformer]).
func NewActivationPoolInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewActivationPoolInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedActivationPoolInformer constructs a new informer for ActivationPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedActivationPoolInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers ActivationPoolIndexers) ActivationPoolIndexInformer {
	return NewTypedActivationPoolInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredActivationPoolInformer constructs a new informer for ActivationPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredActivationPoolInformer]).
func NewFilteredActivationPoolInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedActivationPoolInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredActivationPoolInformer constructs a new informer for ActivationPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredActivationPoolInformer(client kubernetes.Interface, namespace string, resyncPeriod time.Duration, indexers ActivationPoolIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ActivationPoolIndexInformer {
	return NewTypedActivationPoolInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewActivationPoolInformerWithOptions constructs a new informer for ActivationPool type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedActivationPoolInformerWithOptions]).
func NewActivationPoolInformerWithOptions(client kubernetes.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedActivationPoolInformerWithOptions(client, namespace, options)
}

// NewTypedActivationPoolInformerWithOptions constructs a new informer for ActivationPool type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedActivationPoolInformerWithOptions(client kubernetes.Interface, namespace string, options internalinterfaces.InformerOptions) ActivationPoolIndexInformer {
	gvr := schema.GroupVersionResource{Group: "activation.k8s.io", Version: "v1alpha1", Resource: "activationpools"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiactivationv1alpha1.ActivationPool](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ActivationV1alpha1().ActivationPools(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ActivationV1alpha1().ActivationPools(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ActivationV1alpha1().ActivationPools(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ActivationV1alpha1().ActivationPools(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiactivationv1alpha1.ActivationPool{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *activationPoolInformer) defaultInformer(client kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedActivationPoolInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *activationPoolInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *activationPoolInformer) TypedInformer() ActivationPoolIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiactivationv1alpha1.ActivationPool](f.factory.InformerFor(&apiactivationv1alpha1.ActivationPool{}, f.defaultInformer))
}

func (f *activationPoolInformer) Lister() activationv1alpha1.ActivationPoolLister {
	return activationv1alpha1.NewActivationPoolLister(f.Informer().GetIndexer())
}

// ToTypedActivationPoolInformer converts an untyped informer into a TypedActivationPoolInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ActivationPool. If that is not the case, calling type-safe methods of the returned
// TypedActivationPoolInformer leads to runtime panics. A safer alternative is to pass
// around a TypedActivationPoolInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedActivationPoolInformer(informer ActivationPoolInformer) TypedActivationPoolInformer {
	if informer, ok := informer.(TypedActivationPoolInformer); ok {
		return informer
	}
	return &activationPoolTypedInformerAdapter{informer}
}

type activationPoolTypedInformerAdapter struct {
	ActivationPoolInformer
}

func (a *activationPoolTypedInformerAdapter) TypedInformer() ActivationPoolIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiactivationv1alpha1.ActivationPool](a.Informer())
}

// ToActivationPoolIndexInformer converts an untyped informer into a ActivationPoolIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ActivationPool. If that is not the case, calling type-safe methods of the returned
// ActivationPoolIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ActivationPoolIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToActivationPoolIndexInformer(informer cache.SharedIndexInformer) ActivationPoolIndexInformer {
	if informer, ok := informer.(ActivationPoolIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiactivationv1alpha1.ActivationPool](informer)
}
