//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package activation

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationPool) DeepCopyInto(out *ActivationPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationPool.
func (in *ActivationPool) DeepCopy() *ActivationPool {
	if in == nil {
		return nil
	}
	out := new(ActivationPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivationPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationPoolList) DeepCopyInto(out *ActivationPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActivationPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationPoolList.
func (in *ActivationPoolList) DeepCopy() *ActivationPoolList {
	if in == nil {
		return nil
	}
	out := new(ActivationPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivationPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationPoolSpec) DeepCopyInto(out *ActivationPoolSpec) {
	*out = *in
	in.TemplateRef.DeepCopyInto(&out.TemplateRef)
	out.Warm = in.Warm
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(PoolSource)
		**out = **in
	}
	in.Activation.DeepCopyInto(&out.Activation)
	in.Durability.DeepCopyInto(&out.Durability)
	out.Supply = in.Supply
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationPoolSpec.
func (in *ActivationPoolSpec) DeepCopy() *ActivationPoolSpec {
	if in == nil {
		return nil
	}
	out := new(ActivationPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationPoolStatus) DeepCopyInto(out *ActivationPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationPoolStatus.
func (in *ActivationPoolStatus) DeepCopy() *ActivationPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ActivationPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivationSpec) DeepCopyInto(out *ActivationSpec) {
	*out = *in
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Coalescing != nil {
		in, out := &in.Coalescing, &out.Coalescing
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivationSpec.
func (in *ActivationSpec) DeepCopy() *ActivationSpec {
	if in == nil {
		return nil
	}
	out := new(ActivationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DurabilitySpec) DeepCopyInto(out *DurabilitySpec) {
	*out = *in
	if in.Offered != nil {
		in, out := &in.Offered, &out.Offered
		*out = make([]DurabilityTier, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DurabilitySpec.
func (in *DurabilitySpec) DeepCopy() *DurabilitySpec {
	if in == nil {
		return nil
	}
	out := new(DurabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSource) DeepCopyInto(out *PoolSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSource.
func (in *PoolSource) DeepCopy() *PoolSource {
	if in == nil {
		return nil
	}
	out := new(PoolSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupplySpec) DeepCopyInto(out *SupplySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupplySpec.
func (in *SupplySpec) DeepCopy() *SupplySpec {
	if in == nil {
		return nil
	}
	out := new(SupplySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmSpec) DeepCopyInto(out *WarmSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmSpec.
func (in *WarmSpec) DeepCopy() *WarmSpec {
	if in == nil {
		return nil
	}
	out := new(WarmSpec)
	in.DeepCopyInto(out)
	return out
}
